trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*
pr:
  - main

pool:
  vmImage: 'macos-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install JDK'

  - script: |
      python -m pip install --upgrade pip
      python -m pip install six
      echo no | npm install -g nativescript
      ns usage-reporting disable
      ns error-reporting disable
    displayName: 'Install NativeScript CLI'

  - script: |
      npm run setup
    displayName: 'Setup'

  - script: |
      npm start lint
    displayName: 'Lint'

  - script: |
      npm start @awarns.build-all
    displayName: 'Build'

  - script: |
      cd apps/demo
      ns build android
    displayName: 'Build demo'

  - script: |
      ./ci-tools/wait-for-emulator.sh
      npm start android-test-ci &
      ./ci-tools/android-screenrec.sh 180 4
    displayName: 'Test'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(System.DefaultWorkingDirectory)/screenshots
      artifactName: screenshots

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'apps/demo/src/test-reports/**/report.xml'
